# Generated by Django 4.1.6 on 2023-07-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_customeruser_api_delete_userapikey'),
        ('ctm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customer'),
        ),
    ]
