# Generated by Django 4.1 on 2022-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='product name', max_length=255, unique=True),
        ),
    ]
