# Generated by Django 4.0.7 on 2022-09-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
    ]
