# Generated by Django 4.0.7 on 2022-09-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_subcategories_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
