# Generated by Django 4.0.7 on 2023-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
