# Generated by Django 4.0.7 on 2023-09-12 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_visitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 13, 42, 21, 101302)),
        ),
    ]
