# Generated by Django 4.0.7 on 2023-09-29 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_visitor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 18, 26, 52, 142594)),
        ),
    ]
