# Generated by Django 4.1 on 2022-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Seller', 'Seller'), ('Customer', 'Customer')], default='Customer', max_length=100),
        ),
    ]
