# Generated by Django 4.1 on 2022-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleruser',
            name='by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='profile_pic',
            field=models.ImageField(upload_to='Customer/AdminUser/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='profile_pic',
            field=models.ImageField(upload_to='Customer/CustomerUser/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='profile_pic',
            field=models.ImageField(upload_to='Customer/SellerUser/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='profile_pic',
            field=models.ImageField(upload_to='Customer/StaffUser/%Y/%m/%d/'),
        ),
    ]
