# Generated by Django 4.1 on 2022-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_selleruser_by_admin_alter_adminuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='zip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='zip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='zip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='zip',
            field=models.CharField(default='', max_length=255),
        ),
    ]
