# Generated by Django 4.1.6 on 2023-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_editortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
