# Generated by Django 4.1.6 on 2023-07-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_adminuser_address_customeruser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='8fe4d9d230db4f3b9a84b32af9f7c8bd', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='customeruser',
            name='api',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.userapikey'),
        ),
    ]
