# Generated by Django 4.1.6 on 2023-07-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_userapikey_customeruser_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='api',
        ),
        migrations.DeleteModel(
            name='UserApiKey',
        ),
    ]
