# Generated by Django 4.0.7 on 2023-08-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_customeruser_api_delete_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleruser',
            name='company_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
