# Generated by Django 4.0.7 on 2023-09-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
