# Generated by Django 4.0.7 on 2023-09-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_selleruser_company_name'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customer')),
            ],
        ),
    ]
