# Generated by Django 4.1.6 on 2023-06-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_billingaddress_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
