# Generated by Django 4.0.7 on 2023-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_is_closed_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='COD', max_length=255),
        ),
    ]
